### ISSUE TITLE
Jinja Template Issue with Undefined vars

### ISSUE THREAD

**Issue by jandiorio** [redhat-cop/ee_utilities#10]
The existing logic checks if any of the 3 variables (`ee_bindep`, `ee_python`, and `ee_collections`) are defined, then the next stanza checks the length of all 3 causing issues for those that are undefined.  

FILE: `execution_environment.yml.j2`

Here is a possible solution:

```jinja

{% if (ee_bindep is defined and ee_bindep|length ) or
        (ee_python is defined and ee_python|length ) or
        (ee_collections is defined and ee_bindep|length) %}
dependencies:
{% if ee_bindep is defined %}
{%      if ee_bindep|length %}
  system: {{ bindep_file }}
{%      endif %}
{% endif %}
{% if ee_python is defined %}
{%      if ee_python|length %}
  python: {{ python_requirements_file }}
{%      endif %}
{% endif %}
{% if ee_collections is defined %}
{%      if ee_collections|length %}
  galaxy: {{ galaxy_requirements_file }}
{%      endif %}
{% endif %}
{% endif %}
```

**Comment by jangel97** [comment]
I tested your suggestions and they worked in my environment, also it makes sense what you say.
PR: https://github.com/redhat-cop/ee_utilities/pull/11

**Comment by sean-m-sullivan** [comment]
Looks like your PR should resolve this, going to close the issue :)
