### ISSUE TITLE
Variables not well documented

### ISSUE THREAD

**Issue by ansiblejunky** [redhat-cop/ee_utilities#105]
# Summary

Need to document the use of `venv_migrate_show_diff_with_default` variable and `ee_collections` variable. Also add info in the README.md. 

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version

ansible-galaxy collection list

podman --version

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

# Desired Behavior

Documentation states clearly the use of that variable.

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

# STEPS TO REPRODUCE

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by sean-m-sullivan** [comment]
Fixed in the upcoming v3 changes, please review, let me know if we can do more, sorry this has been on backburner for a while.

**Comment by sean-m-sullivan** [comment]
Closing this as we redid everything with the v3 change and no response.
