### ISSUE TITLE
documentation of ee_builder mentions ee_base_image but in code (and examples) base_image is used

### ISSUE THREAD

**Issue by cmasopust** [redhat-cop/ee_utilities#33]
# Summary

The documentation of the ee_builder role has `ee_base_image` as variable for the execution environment definition.
Trying to override the base image using `ee_base_image` fails because in the role is expecting the variable to be `base_image`.

# Issue Type

- Bug Report

# Desired Behavior

Documentation being consistent with the implementation and the examples

# Actual Behavior

Documentation is misleading.

**Comment by sean-m-sullivan** [comment]
This should be fixed as well in latest release of 2.0.2, 2.0.3 will have config fix.
