### ISSUE TITLE
execution_environment.yml does not include ansible.cfg even if ee_create_ansible_config is defined

### ISSUE THREAD

**Issue by cmasopust** [redhat-cop/ee_utilities#34]
# Summary

Subject says it all, the created ansible.cfg is not added to execution_environment.yml. 

# Issue Type

- Bug Report

# Desired Behavior

Generated ansible.cfg should be added to execution_environment.yml

# Actual Behavior

ansible.cfg will be created but neither appear in execution_environment.yml nor in the created image.

**Comment by sean-m-sullivan** [comment]
Fixed with #47
