### ISSUE TITLE
__ee_stream_images should be default, not vars

### ISSUE THREAD

**Issue by williamhanseneric** [redhat-cop/ee_utilities#92]
Disconnected environments may want to override __ee_stream_images to point to their local hub for these images.  Putting this variables in "vars" makes overriding it difficult, it needs to be in defaults.

**Comment by djdanielsson** [comment]
__ee_stream_images ends up pointing to ee_base_image and ee_builder_image which is what you could over ride if you are in a disconnected env 

for more info see https://github.com/redhat-cop/ee_utilities/blob/8699a761bba675f111580ec50d22a84bf783328b/roles/ee_builder/README.md?plain=1#L25

**Comment by Tompage1994** [comment]
Agreed, by convention any variables in the roles which start with `__` can be considered 'internal' variables and therefore should essentially be ignored by the end user. Instead the vars @djdanielsson mentioned should be used to override.

That said, I can see why some confusion could arise from the readme as we do mention this internal variable. Perhaps we remove the following line to prevent this happening?

https://github.com/redhat-cop/ee_utilities/blob/0853cf8782192ae42e3972532919644a27fbbfb3/roles/ee_builder/README.md?plain=1#L33

**Comment by sean-m-sullivan** [comment]
Removed from latest readme, and added a note that these are only used if no base is specified.
